

//Async Higher Order Function :    

const asyncHandler = (fn) => async(req, res, next) => {           // using try-catch 
  try {
     await fn(req, res, next)
  } catch (error) {
    res.status(err.code || 400).json({
        success : false,
        message : err.message
    })
  }
}